### ISSUE TITLE
i am facing a problem when i trying to excute this command 'pip install -r requirements.txt' 

### ISSUE THREAD

**Issue by FatimaElsaadny** [Barqawiz/Shakkala#25] opened 2021-06-30 14:51 UTC
![image](https://user-images.githubusercontent.com/53664496/123997049-3f199c00-d9d0-11eb-9887-f162fcc9b38f.png)

**Comment by Barqawiz** [comment] 2021-06-30 23:01
Thanks Fatima Elsaadny for informing me about the issue, it should be fixed now.

The project updated to new libraries version.

Also as another option you can find a file called (shakkala.yaml) which you can use to build anaconda environment.

Kindly test "pip install -r requirements.txt" and tell me if the issue is resolved.

**Comment by FatimaElsaadny** [comment] 2021-07-01 19:06
installed successfully  but when i import it, it's show me " ModuleNotFoundError: No module named 'Shakkala' "

**Comment by Barqawiz** [comment] 2021-07-03 01:59
It seems it is an issue with your local terminal to reference the file location, please send the error details with the commands.

Try to run the demo file and tell me how it goes:
python demo.py

**Comment by FatimaElsaadny** [comment] 2021-07-03 22:28
it's works fine thanks to you, i handled this model to read from a text
file more than 18.000 char and it works successfully, but takes much time,
about 15 min and there are many lines discarded without diacritization!!
Are there any  ways to enhance the performance of predicted output and time
of working?. thanks

**Comment by Barqawiz** [comment] 2021-07-03 23:59
About the time you can enhance it by running the model on computer that include GPU or in AWS cloud p2, p3 instances.

Shakkal should work with each character, the lines without diacritization might be because the way the sentences spliced or the character encoding.

Try any of the sentences without (diacritization) in Shakkala.com, If it working then this due to one of above processing reason.

**Closed as completed by Barqawiz** 2021-07-03 23:59 UTC

**Comment by FatimaElsaadny** [comment] 2021-07-05 14:08
Thanks Ahmed Barqawiz for your help, the model works well now. The reason
for the long time is that I call the start model and end it after each
read, now file takes one min. for  sentences without (diacritization)
i found a mistake in my code and corrected it. another question please can
i train this model to get better performance?

**Comment by Barqawiz** [comment] 2021-07-07 16:19
You can fine-tune the model. 

It is already trained on lots of data. When you fine tune it make sure to not go for many iterations to avoid overfitting.
